server:
  port: 8080

spring:
  application:
    name: e-commerce-site-service
  datasource:
    url: jdbc:mysql://localhost:3306/e_commerce_service
    username: root
    password: Abhi@2109
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
